config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homepage#index'
  resources :posts do
    resources :image
  end

  namespace :admin do
    resources :posts
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord

  has_many_attached :images
  has_rich_text :content

  PENDING = 'pending'
  REJECTED = 'rejected'
  VALIDATED = 'validated'

  STATUS = [PENDING, REJECTED, VALIDATED].freeze

  STATUS.each do |status|

    scope status, -> { where(status: status) }

    define_method "#{status}?" do
      self.status == status
    end

    define_method "#{status}!" do
      self.status = status
      save
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/posts_controller.rb
# frozen_string_literal: true

module Admin
  class PostsController < ApplicationController
    before_action :set_post, only: %i[show edit update destroy]
    before_action :authenticate_user!

    # GET /posts or /posts.json
    def index
      @posts = Post.all
    end

    # GET /posts/1 or /posts/1.json
    def show; end

    # GET /posts/new
    def new
      @post = Post.new
    end

    # GET /posts/1/edit
    def edit; end

    # POST /posts or /posts.json
    def create
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully created.' }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /posts/1 or /posts/1.json
    def update
      post = Post.find(params[:id])
      if params[:post][:image_ids]
        params[:post][:image_ids].each do |image_id|
          image = post.images.find(image_id)
          image.purge
        end
      end
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to admin_post_path(@post), notice: 'Post was successfully updated.' }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /posts/1 or /posts/1.json
    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to admin_posts_path, notice: 'Post was successfully destroyed.' }
      end
    end


    private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :status, :images, :important, :header, :created_at)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, :notice => 'Vous n\'avez pas les droits pour accéder à cette page'
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    end
  end
end

app/controllers/homepage_controller.rb
# frozen_string_literal: true

class HomepageController < ApplicationController

  def index
    @posts = Post.where(status: 'validated').order(:created_at)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show]

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end

  def show; end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "created"
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
end

private

# Only allow a list of trusted parameters through.
def post_params
  params.require(:post).permit(:title, :content , :status, images: [])
end

private

# Use callbacks to share common setup or constraints between actions.
def set_post
  @post = Post.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
  def device
    agent = request.user_agent
    return "tablet" if agent =~ /(tablet|ipad)|(android(?!.*mobile))/i
    return "mobile" if agent =~ /Mobile/
    return "desktop"
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/posts/_form.html.erb
<div class="container small show-1-nouvelle">
<%= form_with(model: [:admin, @post], local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :header %>
    <%= form.text_field :header %>
  </div>

  <div class="field">
    <%= form.label :titre %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :contenu %>
    <%= form.rich_text_area :content %>
  </div>

  <div class="field">
    <%= form.label :date_de_creation %>
    <%= form.date_field :created_at %>
  </div>



    <% if @post.images.present? %>
      <p>Images actuellement enregistrées (cochez la ou les images que vous souhaitez effacer)</p>
      <% @post.images.each do |image| %>
        <%= form.check_box :image_ids, {multiple: true}, image.id, false %>
        <%= image_tag image, size:"100x100" %> <br>
      <% end %>
    <% end %>




  <div class="field">
    <p> Status du contenu : <%= form.select(:status, options_for_select([['pending'], ['rejected'], ['validated']],@post.status)) %> </p>
  </div>

  <div class="field">
    <p>Mettre en avant ? (cochez la case) <%= form.check_box :important %></p>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/admin/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>


<%= link_to 'Show', admin_post_path(@post) %> |
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.status %></td>
        <td><%= link_to 'Show', admin_post_path(post) %></td>
        <td><%= link_to 'Edit', edit_admin_post_path(post) %></td>
        <td><%= link_to 'Destroy', admin_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_admin_post_path %>

app/views/admin/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/show.html.erb
 <div class="container">
    <p id="notice"><%= notice %></p>

    <div class="d-flex justify-content-center">
      <h2>
        <%= @post.title %>
      </h2>
    </div>

    <div class="d-flex justify-content-center">
      <p>
        <%= @post.content %>
      </p>
    </div>
    <div class="d-flex justify-content-center">
      <bold>Image(s):</bold>
      <% @post.images.each do |img|%>
        <li>
          <%=link_to url_for(img.variant(quality: 60, resize_to_limit: [750, 750])) , :class => "img-thumbnail", :target => "_blank" do%>
            <span class="mgl-thumbnail-sizer"><%= image_tag img.variant(quality: 30, resize_to_fill: [100, 100]) %></span>
          <% end %>
        </li>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <p>
        <strong>Mis en Avant? (carte sur fond bleu): </strong>
        <% if @post.important === true%>
          oui </p>
        <% else %>
          non </p>
        <% end %>
        </p>

    </div>
    <div class="d-flex justify-content-center">
      <p>
        <strong>Status:</strong>
        <%= @post.status %>
      </p>
    </div>
    <div class="d-flex justify-content-center" data-turbolinks="false">
      <%= link_to 'Edit', edit_admin_post_path(@post) %>
      <%= link_to 'Retour', admin_posts_path %>
    </div>
  </div>

app/views/homepage/index.html.erb
<div class="container">
  <div class="text-center m-5">
    <h1 class="display-4">
      <%= image_tag 'escapade_des-nouvelles.png', :alt => 'Des nouvelles de' %>
      <%= image_tag 'escapade_lEscapade.png', :alt => 'l\'escapade' %>
    </h1>
    <% if device == "desktop" %>
      <div class="mgl-big-screens-only class="switch-timeline">
        <span style="color: white;">Frise horizontale</span>
        <div class="form-check form-switch" style="display: inline-block;">
          <input class="form-check-input" type="checkbox" id="check" onclick="changeDisplay()">
          <label class="form-check-label" for="flexSwitchCheckDefault" style="color: white;">Frise verticale</label>
        </div>
      </div>
    <% end %>
  </div>
</div>


<div id="hide" style="opacity: 0.5;">
  <!--vue verticale-->
  <% if device == "tablet" || device == "mobile" %>
  <div id="timeline-display-vertical" style="display:block">
    <% else %>
    <div id="timeline-display-vertical" style="display:none">
      <% end %>
    <div class="timeline " data-vertical-start-position="right" data-vertical-trigger="150px">
      <div class="timeline__wrap">
        <div class="timeline__items">
          <% @posts.order("created_at").reverse.each do |post| %>
            <div class="timeline__item">
              <div class="timeline__content">
                <%if post.important? %>
                  <div class="card text-white bg-primary">
                <%else %>
                  <div class="card">
                <% end %>
                <% if post.images.attached? %>
                    <%= image_tag post.images.last.variant(quality: 80, resize_to_fill: [320, 200]), :class => "card-img-top", :style => "width: 320px"%>
                  <% end %>
                <% if post.header.present? %>
                  <div class="card-header">
                  <%= post.header %>
                  </div>
                <% end %>
                <div class="card-body">
                  <p class="card-date"><%= post.created_at.strftime("%d/%m/%Y") %></p>
                  <h5><%= post.title %></h5>
                  <p><%= post.content %></p>
                  <% if post.images.attached? && post.images.count > 1%>
                    <ul class="mgl-galery">
                      <% post.images.each do |img|%>
                        <%  if img.blob.variable?  %>
                        <li>
                          <%=link_to url_for(img.variant(quality: 60, resize_to_limit: [750, 750])) , :class => "img-thumbnail", :target => "_blank" do%>
                            <span class="mgl-thumbnail-sizer"><%= image_tag img.variant(quality: 20, resize_to_fill: [100, 100]) %></span>
                            <% if img.blob.variable? == false %>
                            <li>
                              <%=link_to url_for(img) , :class => "img-thumbnail", :target => "_blank" do%>
                                <span class="mgl-thumbnail-sizer"><%= image_tag img %></span>
                              <% end %>
                              <% end %>
                              <% end %>
                              <% end %>
                        </li>
                      <% end %>
                  <% end %>
                  </ul>
                  <div class="read-more">
                    <%= link_to "Lire la suite", post_path(post), :class => "btn btn-primary", :target => "_blank" %>
                  </div>
                </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <!--vue horizontale-->
  <% if device == "tablet" || device == "mobile" %>
  <div id="timeline-display-horizontal" style="display:none">
    <% else %>
  <div id="timeline-display-horizontal" style="display:block">
    <% end %>
    <div class="timeline" data-mode="horizontal" data-force-vertical-mode="800" data-rtl-mode="true" >
      <div class="timeline__wrap">
        <div class="timeline__items">
          <% @posts.each do |post| %>
            <div class="timeline__item">
              <div class="timeline__content">
                <%if post.important? %>
                  <div class="card text-white bg-primary">
                    <%else %>
                  <div class="card">
                    <% end %>
                    <% if post.images.attached? %>
                      <%= image_tag post.images.last.variant(quality: 80, resize_to_fill: [320, 200]), :class => "card-img-top"%>
<!--                  faire un crop-->
                    <% end %>
                  <% if post.header.present? %>
                    <div class="card-header">
                    <%= post.header %>
                    </div>
                  <% end %>
                  <div class="card-body">
                    <p class="card-date"><%= post.created_at.strftime("%d/%m/%Y") %></p>
                    <h5><%= post.title %></h5>
                    <%= truncate((post.content.to_plain_text), length: 120, :escape => false) %>
                    <% if post.images.attached? && post.images.count > 1 %>
                      <ul class="mgl-galery">
                        <% post.images.each do |img|%>
                          <%  if img.blob.variable?  %>
                          <li>
                            <%=link_to url_for(img.variant(quality: 60, resize_to_limit: [750, 750])) , :class => "img-thumbnail", :target => "_blank" do%>
                              <span class="mgl-thumbnail-sizer"><%= image_tag img.variant(quality: 20, resize_to_fill: [100, 100]) %></span>
                              <% if img.blob.variable? == false %>
                                <li>
                                  <%=link_to url_for(img) , :class => "img-thumbnail", :target => "_blank" do%>
                                    <span class="mgl-thumbnail-sizer"><%= image_tag img %></span>
                                    <% end %>
                                    <% end %>
                                    <% end %>

<!--                              faire un crop-->
                            <% end %>
                          </li>
                        <% end %>
                    <% end %>
                    </ul>
                    <div class="read-more">
                      <%= link_to "Lire la suite", post_path(post), :class => "btn btn-primary", :target => "_blank" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<!--script pour passer de la vue verticale à la vue horizontale-->


<script>

    let displayBoolean = true
    function changeDisplay() {
        displayBoolean = !displayBoolean
        let displayVertical = document.getElementById("timeline-display-vertical");
        let displayHorizontal = document.getElementById("timeline-display-horizontal");
        if (displayBoolean === false){
            displayVertical.style.display = "block";
            displayHorizontal.style.display = "none";
        } else {
            displayVertical.style.display = "none";
            displayHorizontal.style.display = "block";
        }
    }
</script>

app/views/layouts/_navbar.html.erb
<!--<div class="row justify-content-between">-->
<!--  <div class="col-1">-->
<%#= link_to root_path do %>
<!--      <button type="button" class="btn btn-primary">Accueil</button>-->
<%# end %>
<!--  </div>-->

<!--  <div class="col-2">-->

<%#= link_to new_post_path do %>
<!--      <button type="button" class="btn btn-primary">Ajouter un post</button>-->
<%# end %>
<!--  </div>-->

<!--  <div class="col">-->
<%#= link_to admin_posts_path do %>
<!--      <button type="button" class="btn btn-primary">Administration</button>-->
<%# end %>
<!--  </div>-->

<%# if user_signed_in? %>
<!--    <div class="col">-->
<%#= link_to destroy_user_session_path, method: :delete do %>
<!--        <button type="button" class="btn btn-danger">Déconnexion</button>-->
<%# end %>
<!--    </div>-->

<!--    <p>-->
<%#= link_to edit_user_registration_path do %>
<!--        Connecté comme : <%#= current_user.email %>-->
<%# end %>
<!--    </p>-->

<%# else %>
<!--    <div class="col">-->
<%#= link_to new_user_session_path do %>
<!--        <button type="button" class="btn btn-primary">Connexion</button>-->
<%# end %>
<!--    </div>-->

<!--    <div class="col">-->
<%#= link_to new_user_registration_path do %>
<!--        <button type="button" class="btn btn-info">Inscription</button>-->
<%# end %>
<!--    </div>-->
<%# end %>
<!--</div>-->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1"><%= image_tag 'escapade_logo.png', :class=> "mgl-main-nav-logo"%></span>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="nav">
        <li class="nav-item" data-turbolinks="false">
          <%= link_to "Voir les nouvelles", root_path , :class => "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Poster une nouvelle", new_post_path , :class => "nav-link"%>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Administrer les nouvelles", admin_posts_path , :class => "nav-link"%>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete , :class => "nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>🐸 L'Escapade</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <%= stylesheet_link_tag "all", media: 'all', 'data-turbolinks-track': 'reload'  %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'timeline' %>
  </head>
  <body style="background-image: url(<%= asset_path 'fond-eau.jpg' %>)">

    <%= render 'layouts/navbar' %>
    
    <%= yield %>
    <%= render 'layouts/footer' %>

    <%= javascript_pack_tag 'timeline', 'data-turbolinks-track': 'reload' %>
  </body>

  <!-- Bootstrap CSS -->
<!--  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">-->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</html>

app/views/posts/new.html.erb
<div class="container">

<%= form_with(model: @post, local: true) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center m-5">
    <h1 class="display-4">Poster une nouvelle</h1>
    <p class="mgl-small-screens-only mgl-blue">Toutes les informations sur le formulaire et ses données sont consignées en dessous du formulaire.</p>
  </div>

  <main class="mx-5 mb-5">
    <div class="row align-items-start mgl-flip-column">
      <div class="col-8">
        <form action="/posts" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="qv1959Jiq0mNCT72daxO+n1MSagjKO0hBsgzfA4jba67KsMPZXrrcp+OZ1A6a85TNlI+1zMyZJ+DX8gUjFFAxA==">
          <div class="field">
            <label class="form-label" for="post_title">Titre de la nouvelle <small class="mgl-form-info">- obligatoire</small></label>
            <%= form.text_field :title, class: "form-control", required: true %>
          </div>
          <div class="field">
            <label class="form-label" for="post_content">Texte de la nouvelle  <small class="mgl-form-info">- facultatif</small></label>
            <%= form.rich_text_area :content, class: "form-control" %>
          </div>
          <div class="field">
            <label class="form-label" for="post_images">Images de la nouvelle <small class="mgl-form-info">- facultatives, maximum 6</small></label>
              <%= form.file_field :images, multiple: true, class: "form-control" %>
          </div>

<!-- à développer DEBUT -->
<!--      <div class="field"> -->
<!--        <label class="form-label" for="post_title">Vidéo de la nouvelle  <small class="mgl-form-info">- facultative, maximum 1</small></label> -->
<!--        <p style="color: red; font-weight: bold;">En cours de développement</p> -->
<!--      </div> -->
<!--      <div class="field"> -->
<!--        <label class="form-label" for="post_title">Document PDF la nouvelle <small class="mgl-form-info">- facultatif, maximum 1</small></label> -->
<!--        <p style="color: red; font-weight: bold;">En cours de développement</p> -->
<!--      </div> -->
<!-- à développer FIN -->


          <div class="field">
            <div class="form-check">
              <%= form.check_box :terms_of_service, required: true, :class => "form-check-input", :id => "flexCheckDefault" %>
<!--              <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">-->
              <label class="form-check-label" for="flexCheckDefault">J'accepte les conditions d'utilisations précisées ci-contre (sur petit écran : ci-après)<small class="mgl-form-info"> - obligatoire</small></label>
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Poster la nouvelle</button>
        </form>
      </div>
      <div class="col-4">
        <h2>Pour poster une nouvelle</h2>
        <ul class="mgl-steps-form">
          <li><span class="mgl-steps-form__number">1</span><span> Vous remplissez les champs du formulaire</span></li>
          <li><span class="mgl-steps-form__number">2</span><span> Vous cliquez sur le bouton "Poster une nouvelle"</span></li>
          <li><span class="mgl-steps-form__number">3</span><span> Les admins valident (ou non) la nouvelle</span></li>
          <li><span class="mgl-steps-form__number">4</span><span> Elle apparait dans la frise chronologique</span></li>
        </ul>
        <h2>Conditions d'utilisation</h2>
        <p>les textes, images et vidéo que que vous postez seront publiés sous licence libre CC-Zero
          une fois la nouvelle postée, vous ne pourrez pas la modifier
          la nouvelle pourra être modifiée à des fins de mise en page ou de correction orthographique par les administrateurs et administratrices de l'Escapade
          tout contenu insultant, publicitaire ou contrevenant au droit sera supprimé  par les administrateurs et administratrices de l'Escapade.</p>
        <h2>Contact</h2>
        <p>Contact pour toute réclamation concernant les contenus : <a href="mailto:contact@mairie-donzy.fr">contact@mairie-donzy.fr</a></p>
      </div>
    </div>
  </main>
<% end %>

</div>

app/views/posts/show.html.erb
<div class="container small show-1-nouvelle">
  <p id="notice"><%= notice %></p>

  <div>
    <h1>
      <%= @post.title %>
    </h1>
  </div>

  <div>
    <p>
      <%= @post.content %>
    </p>
  </div>
   <div>
     <h2>Image(s)</h2>
     <ul class="mgl-galery">
     <% @post.images.each do |img|%>
       <li>
         <%=link_to url_for(img.variant(quality: 60, resize_to_limit: [750, 750])) , :class => "img-thumbnail", :target => "_blank" do%>
           <span class="mgl-thumbnail-sizer"><%= image_tag img.variant(quality: 20, resize_to_fill: [100, 100]) %></span>
         <% end %>
       </li>
     <% end %>
     </li>
   </div>
  <div class="d-flex justify-content-center" data-turbolinks="false">
    <%= link_to 'Retour', root_path %>
  </div>
</div>